# Generated by Django 5.2.11 on 2026-02-18 20:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bucket_type', models.CharField(choices=[('BILLS', 'Bills'), ('SAVINGS', 'Savings'), ('DAILY', 'Daily')], default='DAILY', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='wallet.wallettransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='wallet.wallet')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory')),
            ],
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['owner', 'slug'], name='expenses_ex_owner_i_f02bec_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='uniq_default_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'slug'), name='uniq_owner_category_slug'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['student', 'occurred_at'], name='expenses_ex_student_c5cadc_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['wallet', 'occurred_at'], name='expenses_ex_wallet__e2769a_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'occurred_at'], name='expenses_ex_categor_45b7a1_idx'),
        ),
    ]
