# Generated by Django 5.2.11 on 2026-02-16 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Monthly Plan', max_length=80)),
                ('currency', models.CharField(default='XAF', max_length=8)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings_mode', models.CharField(choices=[('NONE', 'None'), ('AMOUNT', 'Fixed amount'), ('PERCENT', 'Percent')], default='NONE', max_length=10)),
                ('savings_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('savings_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='budgeting.budgetplan')),
            ],
        ),
        migrations.AddIndex(
            model_name='budgetplan',
            index=models.Index(fields=['student', 'status', 'created_at'], name='budgeting_b_student_928be4_idx'),
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['plan', 'priority'], name='budgeting_b_plan_id_43b224_idx'),
        ),
    ]
