# Generated by Django 5.2.11 on 2026-02-14 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='XAF', max_length=8)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_type', models.CharField(choices=[('BILLS', 'Bills'), ('SAVINGS', 'Savings'), ('DAILY', 'Daily')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='wallet.wallet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('wallet', 'bucket_type'), name='uniq_wallet_bucket')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_type', models.CharField(choices=[('BILLS', 'Bills'), ('SAVINGS', 'Savings'), ('DAILY', 'Daily')], max_length=10)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('txn_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('ALLOCATION', 'Allocation'), ('EXPENSE', 'Expense'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('external_ref', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_actions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='wallet_wall_wallet__83a8d3_idx'), models.Index(fields=['wallet', 'bucket_type', 'created_at'], name='wallet_wall_wallet__9ec3fa_idx')],
            },
        ),
    ]
